name = "captcha-verification"
main = "src/index.js"
compatibility_date = "2024-08-01"

[vars]
TOKEN_TTL = "1800" # 30 min

# KV namespaces
[[kv_namespaces]]
binding = "REDIRECTS"
id = "142c941cc0664e68b71bce4689bd8771"

[[kv_namespaces]]
binding = "CHALLENGES"
id = "e225f25916364ad687774a686902643c"

