name = "recaptcha"
main = "worker.js/store.js"
compatibility_date = "2025-09-30"

kv_namespaces = [
  { binding = "SHORT_URLS", id = "683937da4cc74da29ee3afccf0fb66cd" }
]

[observability]
enabled = true

[vars]
RECAPTCHA_SECRET = "6Lc2LtkrAAAAALlvfdDuwQ_z2hvmY2zUKHZXcAkd"
