name = "captcha-verification"
main = "src/index.js"
compatibility_date = "2024-08-01"

[vars]
TOKEN_TTL = "1800" # 30 min
API_TOKEN = "d9f4a1c8-3b6f-4a9e-91a7-6b02fef4aa73"

# KV namespaces
[[kv_namespaces]]
binding = "REDIRECTS"
id = "142c941cc0664e68b71bce4689bd8771"

[[kv_namespaces]]
binding = "CHALLENGES"
id = "e225f25916364ad687774a686902643c"

# Static assets (HTML, images)
[assets]
directory = "src" # It will serve files from /src folder
binding = "ASSETS"
