name = "slider-captcha-demo"
main = "worker.js"
compatibility_date = "2023-10-01"

kv_namespaces = [
  { binding = "SHORT_URLS", id = "142c941cc0664e68b71bce4689bd8771" }
]

[site]
bucket = "."        # Serves index.html, style.css, assets/
entry-point = "worker"

[build]
command = ""

# Enable logs
[observability]
logs = true
