name = "slider-captcha"
main = "worker.js"
compatibility_date = "2023-10-01"

kv_namespaces = [
  { binding = "SHORT_URLS", id = "683937da4cc74da29ee3afccf0fb66cd" }
]

[site]
bucket = "./public"
#binding = "ASSETS"

[observability]
enabled = true
