name = "captcha-verification"
main = "main.js"
compatibility_date = "2024-08-01"

kv_namespaces = [
  { binding = "TOKENS_KV", id = "142c941cc0664e68b71bce4689bd8771" }
]

[vars]
TOKEN_TTL = "1800"
TOLERANCE = "5"

[site]
bucket = "./src/html"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
